INSERT INTO CATEGORY VALUES (1,'진로');
INSERT INTO CATEGORY VALUES (2,'관계');
INSERT INTO CATEGORY VALUES (3,'직장');
INSERT INTO CATEGORY VALUES (4,'경제');
INSERT INTO CATEGORY VALUES (5,'학업');
INSERT INTO CATEGORY VALUES (6,'가족');
INSERT INTO CATEGORY VALUES (7,'건강');
INSERT INTO CATEGORY VALUES (8,'기타');