create table USER (
userId bigint generated by default as identity,
username varchar(255) NOT NULL,
email varchar(100) ,
role varchar(100)  NOT NULL,
kakaoId varchar(100)  NOT NULL,
imgUrl varchar(100)  NOT NULL,
primary key(userId)
);

create table USER_AUTH(
userId
)